server:
  port: 13800
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

gcloud:
  # val.json  100002910 - appId  塔吊吊装管理员履职识别 - 事件描述  格式：”appId“:”描述“
  event-name: '{"100002910": "塔吊吊装管理员履职识别","100003428":"未带安全帽识别","100003304":"行人-电子围栏识别"}'
  # 可发送的事件对应的skillType    （app_id:skillType）
  # skillType 类型：
  # 0抽烟行为检测，1烟火检测，2口罩佩戴检测，3睡岗检测，4车辆违规检测，5塔吊吊装管理员履职识别，6电子围栏，
  # 7反光衣颜色识别 8安全帽颜色识别 9安全帽检测
  event-skill-Type: '{"100002910":"5","100003428":"9","100002910":"5","100003304":"6"}'
  # post-event: '{}'
  # 是否发送上传事件
  is-post-event: true
  # 上传文件是否删除
  upload-after-del: false
  # 上传文件保存路径
  # linux /home/gcloud/upload/
  # windows D:/gcloud/upload/
  save-dir: 'D:/event-upload/'
  video-save-dir: 'D:/ai-video/'
  # save-dir: /opt/gongdi/event-server/eventInfo/
  # video-save-dir: '/opt/gongdi/event-server/ai-video/'
  # 视频推理类型对应的AI服务接口地址
  video-predict-type: '{"vest":"http://192.168.19.251:9090/api/inflet/v1/tasks/e30bb34a-dcd9-4d95-8714-38df8d680815/predict","helmet":"http://192.168.19.240:9090/api/inflet/v1/tasks/7f07d183-bc79-4d81-b624-8236bc95f337/predict"}'
  # 1/2 意思是每隔2秒生成一张图片
  predict-frame-rate: '1/2'
  beijing:
    # 事件对应的视频推理类型  （app_id:videoType）事件类型：0-安全帽监测、1-反光衣监测、15-安全帽+人脸识别、16-反光衣+人脸识别
    # 6-吸烟 7-人员聚集 17-电子围栏 9-车辆违停 11-睡岗 14-人脸（抓拍/识别）
    # event-Type: '{"100004606":"0","100004540":"1","100004955":"7","100003304":"17","100004968":"9"}'
    # 人脸
    event-Type: '{"100004606":"0","100004540":"1","100004955":"7","100003304":"17","100004968":"9","100005441":"14","100003428":"15","100004540":"16"}'
    # 事件上报地址
    #event-upload-url: 'http://kc.scsc.tech/jeecg-boot/kc-helmet-service/tb/open/video/analysis'
    # event-upload-url: 'http://192.168.19.13:13800/report'
    event-upload-url: 'http://192.168.19.13:8032/face_report'
    ai-face-url: 'http://192.168.19.25:8032/face'
    # ai-face-url: 'http://192.168.19.13:8032/face'
    # 反光衣人头距离比较远，预计偏移量需要设置大一些
    face_max_offset: 100

  gddi:
    username: 'admin'
    password: '123456'

  upload:
    jky:
      #  方案二（目前使用）
      # 建科院 - 提供的地址
      picUploadUrl: http://14.29.161.78:8822/api/iot/dataPush/dataReportGY
#      picUploadUrl: http://127.0.0.1:8080/api/iot/dataPush/dataReportGY
      # 方案一的配置 （暂无用）
      eventInfoUploadUrl: http://localhost:8080/eventInfo
